
# 提取里面的日语翻译
data = {
    "Light Paint" : "",
    "Adjust Light" : "",
    "Mesh Light Paint" : "",
    "Tube Light Paint" : "",
    "Subdivision" : "",
    "Path" : "",
    "Surface" : "",
    "Sky Paint" : "",
    "Method:" : "",
    "Sun Paint" : "",
    "Shadow Paint" : "",
    "Light Painter Gobos" : "",
    "Gobos are best with point or spot lamps." : "",
    "Results may not be as expected." : "",
    "Paint Flag" : "",
    "Adds mesh flag(s) to shadow surfaces specified by selected lights and annotations" : "",
    "Factor" : "",
    "Position between light and surface (0 is at the light, 1 is at the surface)" : "",
    "Offset" : "",
    "Sun lamp\'s offset from annotation(s) along specified axis" : "",
    "Color" : "",
    "Material color of the flag" : "",
    "Opacity" : "",
    "Material transparency of the flag" : "",
    "Add Lamp Texture" : "",
    "Adds texture to lamp to add variation" : "",
    "Remove Lamp Texture" : "",
    "Removes texture from lamp" : "",
    "Adjust Lamp" : "",
    "Adjusts active lamp\'s position and rotation to light surfaces specified by annotations" : "",
    "Method" : "",
    "Method to determine sun direction" : "",
    "Azimuth Samples" : "",
    "Samples of normals around the azimuth. " : "",
    "Elevation Samples" : "",
    "Samples of normals from the horizon to the maximum elevation. " : "",
    "Max Sun Elevation" : "",
    "Tested normals will be scaled to at most this elevation." : "",
    "Angle" : "",
    "Angular diameter of the Sun as seen from the Earth" : "",
    "Power" : "",
    "Sun lamp\'s emit value" : "",
    "Occlusion" : "",
    "Casts rays to determine occlusion and optimal direction for visibility" : "",
    "Average" : "",
    "Uses average of normals" : "",
    "Paint Lamp" : "",
    "Adds lamp to light surfaces specified by annotations" : "",
    "Lamp Type" : "",
    "Relative" : "",
    "Lamp power scales based on distance, relative to 1m" : "",
    "Area light\'s emit value" : "",
    "Radius" : "",
    "Light size for ray shadow sampling" : "",
    "Minimum size" : "",
    "Area lamp size will be clamped to these minimum values" : "",
    "Shape" : "",
    "Determine axis of offset" : "",
    "Rectangle" : "",
    "Square" : "",
    "Disk" : "",
    "Ellipse" : "",
    "Paint Mesh Light" : "",
    "Adds mesh light to light surfaces specified by annotations" : "",
    "Flatten" : "",
    "If checked, projected vertices will be flattened before processing the convex hull" : "",
    "Emit Value" : "",
    "Emission shader\'s emit value" : "",
    "Adds or repositions mesh tube to light surfaces specified by annotations" : "",
    "Merge by distance" : "",
    "Merge adjacent vertices closer than this distance" : "",
    "Wire radius" : "",
    "Smooth shading" : "",
    "If checked, skin modifier will set smooth faces" : "",

    "Wire path Subdivision" : "",
    "Subdivision level to smooth the wire path" : "",
    "Wire surface subdivision" : "",
    "Subdivision level to smooth the wire\'s surface" : "",
    "Light Color" : "",
    "Offset Axis" : "",
    "Y axis" : "",
    "Along the global Y axis" : "",
    "Z axis" : "",
    "Along the global Z axis" : "",
    "Normal" : "",
    "Along surface normals" : "",
    "Rim lighting" : "",
    "Positions light to reflect onto the specified surface directly into the scene camera" : "",
    "X axis" : "",
    "Along the global X axis" : "",
    "Paint Sky" : "",
    "Rotates world sky texture to light surfaces specified by annotations" : "",
    "Sky Model" : "",
    "Model used by sky texture node" : "",
    "Sun size" : "",
    "Angular size of the sun" : "",
    "Sun light\'s intensity" : "",
    "Sky Texture Model:" : "",
    "Paint Sun" : "",
    "Adds sun lamp to light surfaces specified by annotations" : "",
    "Sun light\'s emit value" : "",
    "Nishita" : "",
    "Preetham" : "",
    "Camera" : "",
    "If unchecked, object will not be directly visible by camera (although it will still emit light)" : "",
    "Diffuse" : "",
    "If unchecked, object will not be directly visible by diffuse rays" : "",
    "Specular" : "",
    "If unchecked, object will not be directly visible by specular or glossy rays" : "",
    "Volume" : "",
    "If unchecked, object will not be directly visible by volumetric rays" : "",
    "Ray visibility" : "",
    ##base_tool#
    'paint line':'',
    'erase':'',
    'new stroke':'',
    'local view':'',

    ##flag_tool#
    'Offset (for sun lamps)': '',
    'Opacity': '',
    'lamp factor mode': '',
    'sun lamp offset mode': '',
    'opacity mode': '',
    
    'ON': '开启',
    'OFF': '关闭',

    ##lamp_adjust_tool.py##
    'Offset': '',
    'Lamp radius': '',
    
    'offset mode': '',
    'radius mode': '',
    'power mode': '',
    'relative power': '',


    'Lamp radius': '',

    'flatten': '',
    'Tube radius': '',
    'tube radius mode': '',


    ##sky_tool#
    'Sun size': '',
    'Sun lamp radius': '',
    'sun radius mode': '',
}
